# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  container: 'ocaml/opam2'
  steps:
  - script: |
      opam install astring alcotest odoc
      dune build
      dune runtest -f
      dune build @doc
