name: Check formatting
on:
  pull_request:
jobs:
  build:
    name: Format OCaml code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: avsm/setup-ocaml@v1.0
        with:
          ocaml-version: 4.09.0
      - name: Install dependencies
        run: opam install dune ocamlformat
      - name: Build
        run: opam exec -- dune build
      - name: Format
        run: opam exec -- dune build @fmt --auto-promote
