name: RoutesTest

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
        ocaml-version:
          - "5"
          - "4"
    steps:
      - uses: actions/checkout@v6
      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: ${{ matrix.operating-system == 'ubuntu-latest' }}
      - name: Install dependencies
        run: |
          opam pin add routes.dev -n .
          opam install -t . --deps-only
      - name: Run tests
        run: |
          opam exec -- dune runtest
      - name: Build examples
        run: |
          opam exec -- dune build @example
